const OWNER="Golu171",REPO="study-notes",BRANCH="main";
const DEFAULT_FOLDER="HARYANA-GK/HARYANA-CURRENT";
const MAX_FILE_SIZE=20*1024*1024,RETRIES=8,WEBHOOK_SECRET="study-notes-webhook-2026";
const TG_TIMEOUT=30000,DL_TIMEOUT=60000,GH_TIMEOUT=45000,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const RAM_PANEL=new Map();

export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==="GET")return new Response("Study Notes Bot OK");if(req.method!=="POST"||u.pathname!=="/telegram")return new Response("Not Found",{status:404});if(req.headers.get("X-Telegram-Bot-Api-Secret-Token")!==WEBHOOK_SECRET)return new Response("Unauthorized",{status:401});try{ctx.waitUntil(processUpdate(await req.json(),env));return new Response("OK")}catch{return new Response("Bad Request",{status:400})}},async queue(batch,env){for(const msg of batch.messages){const j=msg.body;try{if(await isStopped(env,j.chat_id)&&!j.auto){await env.UPLOAD_QUEUE.send(j,{delaySeconds:30});msg.ack();continue}if(j.type==="delete")await processDeleteJob(j,env);else await processUploadJob(j,env);msg.ack()}catch(e){if(e.message==="__PAUSED__"){await env.UPLOAD_QUEUE.send(j,{delaySeconds:30});msg.ack()}else{console.error("QUEUE",e);if((msg.attempts||1)>3){msg.ack();await sendMessage(env,j.panel_chat||j.chat_id,`❌ Failed: ${j.file_name||j.name}\nReason: Max queue retries reached.`,{disable_notification:true})}else msg.retry({delaySeconds:15*(msg.attempts||1)})}}}}};

async function processUpdate(u,e){try{if(!e.BOT_STATE||!e.UPLOAD_QUEUE){const c=u.message?.chat?.id;if(c)await sendMessage(e,c,"⚠️ ERROR: Cloudflare Bindings (BOT_STATE or UPLOAD_QUEUE) missing hain!");return}if(u.message)await handleMessage(u.message,e);else if(u.channel_post)await handleChannelPost(u.channel_post,e)}catch(x){console.error("UPDATE",x)}}
async function handleMessage(m,e){const chat=String(m.chat?.id||""),uid=String(m.from?.id||"");if(!chat||!uid)return;if(m.text?.startsWith("/"))return handleCommand(m,e);if(!m.document)return;if(!(await isStaff(e,uid)))return sendMessage(e,chat,"❌ Access denied.");if(await isStopped(e,chat))return sendMessage(e,chat,"🛑 Tumhari processing STOPPED hai.");await enqueueUpload(m.document,chat,uid,e,false,m.message_id)}
async function handleChannelPost(m,e){if(await e.BOT_STATE.get("auto")!=="on")return;const ch=await e.BOT_STATE.get("channel_id");if(!ch||String(ch)!==String(m.chat?.id)||!m.document)return;await enqueueUpload(m.document,String(m.chat.id),String(m.sender_chat?.id||m.chat.id),e,true,m.message_id||null)}

async function handleCommand(m,e){const chat=String(m.chat.id),uid=String(m.from.id),parts=(m.text||"").trim().split(/\s+/),cmd=parts[0].split("@")[0].toLowerCase(),arg=parts.slice(1).join(" ").trim();
if(cmd==="/start")return sendMessage(e,chat,`📚 Study Notes Bot

/setfolder PATH
/mkdir PATH
/setchannel ID
/auto on
/auto off
/status
/delete
/delete FOLDER
/delete 1 3 5
/addadmin USER_ID
/removeadmin USER_ID
/admins
/stop
/resume

📌 Upload folder: KV current folder
⚡ Upload: 1 KV READ, 0 KV WRITE
🟢 Auto ON = channel + RAM live panel`);
if(cmd==="/stop"){if(!(await isStaff(e,uid)))return sendMessage(e,chat,"❌ Access denied.");await e.BOT_STATE.put(`stop:${chat}`,"1",{expirationTtl:604800});return sendMessage(e,chat,"🛑 Processing STOPPED. Pending jobs pause rahenge.")}
if(cmd==="/resume"){if(!(await isStaff(e,uid)))return sendMessage(e,chat,"❌ Access denied.");await e.BOT_STATE.delete(`stop:${chat}`);return sendMessage(e,chat,"▶️ Processing RESUMED. Pending jobs aage badhenge.")}
const owner=await e.BOT_STATE.get("owner_id"),own=!!owner&&String(owner)===uid,admin=!own&&await isAdmin(e,uid);
if(["/addadmin","/removeadmin","/admins"].includes(cmd)){if(!own)return sendMessage(e,chat,"❌ Sirf owner ye command use kar sakta hai.");let a=await getAdmins(e);if(cmd==="/admins")return sendMessage(e,chat,a.length?`👥 Admins:\n\n${a.map((x,i)=>`${i+1}. ${x}`).join("\n")}`:"👥 Koi admin nahi hai.");if(!/^\d+$/.test(arg))return sendMessage(e,chat,`Use:\n${cmd} USER_ID`);if(cmd==="/addadmin"){if(!a.includes(arg))a.push(arg);await e.BOT_STATE.put("admins",JSON.stringify(a));return sendMessage(e,chat,`✅ Admin added: ${arg}`)}a=a.filter(x=>x!==arg);await e.BOT_STATE.put("admins",JSON.stringify(a));return sendMessage(e,chat,`✅ Admin removed: ${arg}`)}
if(!own&&!admin)return sendMessage(e,chat,"❌ Access denied.");
if(cmd==="/setfolder"){const f=cleanPath(arg);if(!f)return sendMessage(e,chat,"❌ Invalid folder path.");await e.BOT_STATE.put("folder",f);return sendMessage(e,chat,`📁 Current folder set:\n${f}`)}
if(cmd==="/mkdir"){const f=cleanPath(arg);if(!f)return sendMessage(e,chat,"❌ Invalid folder path.");const r=await githubPut(e,`${f}/.gitkeep`,"",`Create folder ${f}`);return sendMessage(e,chat,r.ok?`✅ Folder ready:\n${f}`:`❌ ${r.message}`)}
if(cmd==="/setchannel"){if(!arg)return sendMessage(e,chat,"Use /setchannel CHANNEL_ID");await e.BOT_STATE.put("channel_id",arg);return sendMessage(e,chat,`📢 Channel set:\n${arg}`)}
if(cmd==="/auto"){const v=arg.toLowerCase();if(v!=="on"&&v!=="off")return sendMessage(e,chat,"Use /auto on or /auto off");await e.BOT_STATE.put("auto",v);return sendMessage(e,chat,v==="on"?"🟢 Auto ON":"🔴 Auto OFF")}
if(cmd==="/status")return status(e,chat);if(cmd==="/delete")return deleteCommand(e,chat,arg);return sendMessage(e,chat,"❌ Unknown command. /start use karo.")}

async function enqueueUpload(doc,chat,uid,e,auto,msg_id){const name=cleanUploadName(doc.file_name||"");if(!name){if(!auto)await sendMessage(e,chat,"❌ Sirf .html ya .json file allowed hai.",{reply_to_message_id:msg_id});return}if((doc.file_size||0)>MAX_FILE_SIZE){if(!auto)await sendMessage(e,chat,"❌ Maximum file size 20 MB hai.",{reply_to_message_id:msg_id});return}const folder=await e.BOT_STATE.get("folder")||DEFAULT_FOLDER;let panel_chat=chat;if(auto){const owner=await e.BOT_STATE.get("owner_id");panel_chat=owner?String(owner):chat}await e.UPLOAD_QUEUE.send({type:"upload",chat_id:chat,panel_chat,file_id:doc.file_id,file_name:name,folder,auto,msg_id})}

function pkey(j){return String(j.panel_chat||j.chat_id)+"|"+j.folder}function getPanel(j){const k=pkey(j),now=Date.now();let p=RAM_PANEL.get(k);if(!p||now-p.time>10*60*1000){p={msg_id:null,done:0,skip:0,fail:0,time:now,auto:j.auto};RAM_PANEL.set(k,p)}p.time=now;return p}
async function renderPanel(e,j,p,processing=""){if(!p.msg_id){const r=await tgCall(e,"sendMessage",{chat_id:j.panel_chat||j.chat_id,text:`📊 <b>SMART LIVE PANEL</b> ${p.auto?"(🟢 AUTO ON)":""}\n📁 <code>${esc(j.folder)}</code>\n\n⏳ Starting...`,parse_mode:"HTML"});if(r?.ok)p.msg_id=r.result.message_id}if(!p.msg_id)return;await tgCall(e,"editMessageText",{chat_id:j.panel_chat||j.chat_id,message_id:p.msg_id,text:`📊 <b>SMART LIVE PANEL</b> ${p.auto?"(🟢 AUTO ON)":""}\n📁 <code>${esc(j.folder)}</code>\n\n✅ Uploaded : ${p.done}\n⏭️ Skipped  : ${p.skip}\n❌ Failed   : ${p.fail}${processing?`\n\n⚙️ <i>Processing:</i>\n📄 <code>${esc(processing)}</code>`:"\n\n⏳ <i>Waiting for next file...</i>"}`,parse_mode:"HTML"})}
async function processUploadJob(j,e){if(await isStopped(e,j.chat_id)&&!j.auto)throw Error("__PAUSED__");const p=getPanel(j);await renderPanel(e,j,p,j.file_name);let r;try{r=await processDocument(j,e)}catch(x){if(x.message==="__PAUSED__")throw x;r={ok:false,message:x.message||"Unknown error"}}if(r.ok)r.skipped?p.skip++:p.done++;else p.fail++;if(j.msg_id)try{await tgCall(e,"setMessageReaction",{chat_id:j.chat_id,message_id:j.msg_id,reaction:[{type:"emoji",emoji:r.ok?(r.skipped?"🤷‍♂️":"👍"):"👎"}]})}catch{}await renderPanel(e,j,p,"");if(!r.ok)await sendMessage(e,j.auto?(j.panel_chat||j.chat_id):j.chat_id,`❌ Failed: ${j.file_name}\nReason: ${r.message}`,j.auto?{}:{reply_to_message_id:j.msg_id,disable_notification:true});await sleep(300)}

async function processDocument(j,e){if(await isStopped(e,j.chat_id)&&!j.auto)throw Error("__PAUSED__");const direct=/\.json$/i.test(j.file_name),target=direct?j.file_name:j.file_name.replace(/\.(html|htm)$/i,".json");const ex=await githubFileExists(e,`${j.folder}/${target}`);if(!ex.ok)throw Error("GitHub existing-file check failed: "+ex.message);if(ex.exists)return{ok:true,skipped:true,questions:0,jsonName:target};const f=await telegramGetFile(e,j.file_id);if(!f.ok)throw Error("Telegram file lookup failed.");const r=await fetchTimeout(`https://api.telegram.org/file/bot${e.BOT_TOKEN}/${f.result.file_path}`,{},DL_TIMEOUT);if(!r.ok)throw Error("Telegram download failed.");const buf=await r.arrayBuffer();if(buf.byteLength>MAX_FILE_SIZE)throw Error("File 20 MB se badi hai.");const text=new TextDecoder().decode(buf);if(direct){let data;try{data=JSON.parse(text)}catch(x){throw Error("Invalid JSON: "+x.message)}if(!Array.isArray(data))throw Error("JSON root array [...] hona chahiye.");const g=await githubPut(e,`${j.folder}/${j.file_name}`,textToBase64(text),`Add JSON ${j.file_name}`);if(!g.ok)throw Error(g.message);return{ok:true,questions:data.length,jsonName:j.file_name}}const q=htmlToQuizJson(text);if(!q.ok)throw Error(q.message);if(await isStopped(e,j.chat_id)&&!j.auto)throw Error("__PAUSED__");const json=j.file_name.replace(/\.(html|htm)$/i,".json"),g=await githubPut(e,`${j.folder}/${json}`,textToBase64(JSON.stringify(q.questions,null,2)),`Add JSON ${json}`);if(!g.ok)throw Error(g.message);return{ok:true,questions:q.questions.length,jsonName:json}}

async function deleteCommand(e,chat,arg){const folder=await e.BOT_STATE.get("folder")||DEFAULT_FOLDER,tokens=arg.split(/[\s,]+/).filter(Boolean),nums=tokens.length&&tokens.every(x=>/^\d+$/.test(x));if(nums){const r=await githubList(e,folder);if(!r.ok)return sendMessage(e,chat,`❌ Folder nahi mila:\n${folder}`);const files=r.items.filter(x=>x.type==="file"&&/\.(html?|json)$/i.test(x.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:"base"})),sel=[...new Set(tokens.map(Number))];if(sel.some(n=>n<1||n>files.length))return sendMessage(e,chat,`❌ Number 1-${files.length} ke beech hona chahiye.`);for(const n of sel)await e.UPLOAD_QUEUE.send({type:"delete",chat_id:chat,path:files[n-1].path,name:files[n-1].name,folder});return sendMessage(e,chat,`📥 Delete Queue me ${sel.length} files add ho gayi.`)}const listFolder=cleanPath(arg)||folder,r=await githubList(e,listFolder);if(!r.ok)return sendMessage(e,chat,`❌ Folder nahi mila:\n${listFolder}`);const files=r.items.filter(x=>x.type==="file"&&/\.(html?|json)$/i.test(x.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:"base"}));if(!files.length)return sendMessage(e,chat,`📁 Is folder me HTML/JSON file nahi mili.\n\n${listFolder}`);let footer=`🗑️ Delete selected:\n/delete 1 3 5`;if(listFolder!==folder)footer=`⚠️ Ye current active folder nahi hai.\n/setfolder ${listFolder}\n\n/delete 1 3 5`;return sendMessage(e,chat,`📁 Folder:\n${listFolder}\n\n${files.map((x,i)=>`${i+1}. ${x.name}`).join("\n")}\n\n${footer}`)}
async function processDeleteJob(j,e){if(await isStopped(e,j.chat_id))throw Error("__PAUSED__");let r;try{r=await githubDelete(e,j.path,`Delete ${j.name}`)}catch(x){r={ok:false,message:x.message}}await sendMessage(e,j.chat_id,r.ok?`🗑️ Deleted: ${j.name}`:`❌ Delete Failed: ${j.name}\nReason: ${r.message}`,{disable_notification:true});await sleep(300)}

async function status(e,chat){const[f,a,ch,s,admins]=await Promise.all([e.BOT_STATE.get("folder"),e.BOT_STATE.get("auto"),e.BOT_STATE.get("channel_id"),isStopped(e,chat),getAdmins(e)]);return sendMessage(e,chat,`📊 STATUS\n\nOperations : ${s?"🛑 STOPPED":"🟢 RUNNING"}\nAuto       : ${(a||"off").toUpperCase()}\nFolder     : ${f||DEFAULT_FOLDER}\nChannel    : ${ch||"Not set"}\nAdmins     : ${admins.length}\n\nKV:\n• Upload = 1 READ, 0 WRITE\n• Existing GitHub JSON = SKIP\n• Auto ON = RAM Live Panel 🚀`)}
async function getAdmins(e){try{const a=JSON.parse(await e.BOT_STATE.get("admins")||"[]");return Array.isArray(a)?a.map(String):[]}catch{return[]}}async function isAdmin(e,id){return(await getAdmins(e)).includes(String(id))}async function isStaff(e,id){const o=await e.BOT_STATE.get("owner_id");return!!o&&(String(o)===String(id)||await isAdmin(e,id))}async function isStopped(e,id){return(await e.BOT_STATE.get(`stop:${id}`))==="1"}

/* Robust literal JavaScript parser: replaces sanitizeJS()+JSON.parse(). */
class JSValueParser{constructor(s){this.s=s;this.i=0;this.n=s.length}skip(){for(;;){while(this.i<this.n&&/\s/.test(this.s[this.i]))this.i++;if(this.s.startsWith("//",this.i)){this.i+=2;while(this.i<this.n&&this.s[this.i]!=="\n")this.i++;continue}if(this.s.startsWith("/*",this.i)){this.i+=2;const k=this.s.indexOf("*/",this.i);this.i=k<0?this.n:k+2;continue}break}}parse(){this.skip();const v=this.value();this.skip();if(this.i<this.n)throw Error(`Unexpected token '${this.s[this.i]}' at position ${this.i}`);return v}value(){this.skip();if(this.i>=this.n)throw Error("Unexpected end of value");const c=this.s[this.i];if(c==="[")return this.array();if(c==="{")return this.object();if(c==="'"||c==='"'||c==="`")return this.string();const z=this.s.slice(this.i),kw=z.match(/^(true|false|null|undefined)\b/);if(kw){this.i+=kw[0].length;return kw[1]==="true"?true:kw[1]==="false"?false:null}const num=z.match(/^-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/);if(num){this.i+=num[0].length;return Number(num[0])}const id=z.match(/^[A-Za-z_$][\w$-]*/);if(id){this.i+=id[0].length;return id[0]}throw Error(`Unexpected token '${c}' at position ${this.i}`)}string(){const q=this.s[this.i++];let o="";while(this.i<this.n){const c=this.s[this.i++];if(c===q)return o;if(c!=="\\"){o+=c;continue}if(this.i>=this.n){o+="\\";break}const e=this.s[this.i++],m={n:"\n",r:"\r",t:"\t",b:"\b",f:"\f",v:"\v",0:"\0"};if(m[e]!==undefined)o+=m[e];else if(e==="x"&&/^[0-9a-fA-F]{2}/.test(this.s.slice(this.i,this.i+2))){o+=String.fromCharCode(parseInt(this.s.slice(this.i,this.i+2),16));this.i+=2}else if(e==="u"&&/^[0-9a-fA-F]{4}/.test(this.s.slice(this.i,this.i+4))){o+=String.fromCharCode(parseInt(this.s.slice(this.i,this.i+4),16));this.i+=4}else if(e==="\n"){}else if(e==="\r"){if(this.s[this.i]==="\n")this.i++}else o+=e}throw Error("Unterminated string")}array(){const a=[];this.i++;this.skip();if(this.s[this.i]==="]"){this.i++;return a}for(;;){a.push(this.value());this.skip();if(this.s[this.i]===","){this.i++;this.skip();if(this.s[this.i]==="]"){this.i++;return a}continue}if(this.s[this.i]==="]"){this.i++;return a}throw Error(`Expected ',' or ']' at position ${this.i}`)}}object(){const o={};this.i++;this.skip();if(this.s[this.i]==="}"){this.i++;return o}for(;;){this.skip();let k,c=this.s[this.i];if(c==="'"||c==='"'||c==="`")k=this.string();else{const m=this.s.slice(this.i).match(/^[A-Za-z_$][\w$-]*/);if(!m)throw Error(`Invalid object key at position ${this.i}`);k=m[0];this.i+=k.length}this.skip();if(this.s[this.i]!==":")throw Error(`Expected ':' after property '${k}' at position ${this.i}`);this.i++;o[k]=this.value();this.skip();if(this.s[this.i]===","){this.i++;this.skip();if(this.s[this.i]==="}"){this.i++;return o}continue}if(this.s[this.i]==="}"){this.i++;return o}throw Error(`Expected ',' or '}' after property '${k}' at position ${this.i}`)}}}
function htmlToQuizJson(s){let m=s.match(/(?:const|let|var)\s+Qs\s*=\s*/i)||s.match(/(?:const|let|var)\s+Q_DATA\s*=\s*/i);if(!m)return{ok:false,message:"Qs / Q_DATA nahi mila."};const a=extractBalanced(s,m.index+m[0].length,"[","]");if(!a)return{ok:false,message:"Qs/Q_DATA array complete nahi mili."};try{const q=new JSValueParser(a).parse();if(!Array.isArray(q)||!q.length)return{ok:false,message:"Qs / Q_DATA empty hai."};return{ok:true,questions:q}}catch(x){return{ok:false,message:`JS parser error: ${x.message}`}}}
function extractBalanced(s,start,open,close){let d=0,str="",esc=false;for(let i=start;i<s.length;i++){const c=s[i];if(str){if(esc)esc=false;else if(c==="\\")esc=true;else if(c===str)str="";continue}if(c==='"'||c==="'"||c==="`"){str=c;continue}if(c===open)d++;else if(c===close&&--d===0)return s.slice(start,i+1)}return null}
function cleanPath(p){const v=String(p||"").trim().replace(/^\/|\/$/g,"");return(v&&!v.includes("..")&&!v.includes("\\")&&!v.includes("//")&&!/[<>:"|?*]/.test(v))?v:null}function cleanUploadName(n){const v=String(n||"").trim();return(v&&!v.includes("/")&&!v.includes("\\")&&!v.includes("..")&&/\.(html?|json)$/i.test(v))?v:null}function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function textToBase64(t){const b=new TextEncoder().encode(t),c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";let o="",i=0;while(i<b.length-2){const x=(b[i++]<<16)|(b[i++]<<8)|b[i++];o+=c[(x>>18)&63]+c[(x>>12)&63]+c[(x>>6)&63]+c[x&63]}if(i<b.length){let x=b[i++];if(i<b.length){x=(x<<8)|b[i];o+=c[(x>>10)&63]+c[(x>>4)&63]+c[(x<<2)&63]+"="}else o+=c[(x>>2)&63]+c[(x<<4)&63]+"=="}return o}

function gh(e){return{Authorization:`Bearer ${e.GITHUB_TOKEN}`,Accept:"application/vnd.github+json","Content-Type":"application/json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"study-notes-bot"}}function ghUrl(p){return`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p.split("/").map(encodeURIComponent).join("/")}`}
async function githubFileExists(e,path){const u=ghUrl(path);for(let i=1;i<=RETRIES;i++)try{const r=await fetchTimeout(`${u}?ref=${encodeURIComponent(BRANCH)}`,{headers:gh(e)},GH_TIMEOUT);if(r.status===200)return{ok:true,exists:true};if(r.status===404)return{ok:true,exists:false};if(r.status===429||r.status>=500){if(i===RETRIES)return{ok:false,exists:false,message:`GitHub check failed (${r.status})`};await sleep(i*1000);continue}return{ok:false,exists:false,message:(await r.text()).slice(0,300)}catch(x){if(i===RETRIES)return{ok:false,exists:false,message:x.message};await sleep(i*1000)}return{ok:false,exists:false,message:"GitHub file check failed."}}
async function githubPut(e,path,content,message){const u=ghUrl(path);for(let i=1;i<=RETRIES;i++)try{let sha;const x=await fetchTimeout(`${u}?ref=${encodeURIComponent(BRANCH)}`,{headers:gh(e)},GH_TIMEOUT);if(x.ok)sha=(await x.json()).sha;else if(x.status!==404)return{ok:false,message:(await x.text()).slice(0,300)};const body={message,content,branch:BRANCH};if(sha)body.sha=sha;const r=await fetchTimeout(u,{method:"PUT",headers:gh(e),body:JSON.stringify(body)},GH_TIMEOUT);if(r.ok)return{ok:true};if(![409,422].includes(r.status)||i===RETRIES)return{ok:false,message:(await r.text()).slice(0,300)}}catch(x){if(i===RETRIES)return{ok:false,message:x.message}}finally{if(i<RETRIES)await sleep(i*700)}return{ok:false,message:"GitHub retry limit reached."}}
async function githubList(e,path){const r=await fetchTimeout(`${ghUrl(path)}?ref=${encodeURIComponent(BRANCH)}`,{headers:gh(e)},GH_TIMEOUT);if(!r.ok)return{ok:false,items:[]};const d=await r.json();return{ok:true,items:Array.isArray(d)?d:[]}}
async function githubDelete(e,path,message){const u=ghUrl(path);for(let i=1;i<=RETRIES;i++)try{const x=await fetchTimeout(`${u}?ref=${encodeURIComponent(BRANCH)}`,{headers:gh(e)},GH_TIMEOUT);if(x.status===404)return{ok:false,message:"File GitHub par nahi mila."};if(!x.ok)throw Error("GitHub file lookup failed");const d=await x.json(),r=await fetchTimeout(u,{method:"DELETE",headers:gh(e),body:JSON.stringify({message,sha:d.sha,branch:BRANCH})},GH_TIMEOUT);if(r.ok)return{ok:true};if(![409,422].includes(r.status)||i===RETRIES)return{ok:false,message:(await r.text()).slice(0,300)}}catch(x){if(i===RETRIES)return{ok:false,message:x.message}}finally{if(i<RETRIES)await sleep(i*700)}return{ok:false,message:"GitHub delete retry limit reached."}}
async function telegramGetFile(e,id){for(let i=1;i<=3;i++)try{const r=await fetchTimeout(`https://api.telegram.org/bot${e.BOT_TOKEN}/getFile?file_id=${encodeURIComponent(id)}`,{},TG_TIMEOUT),d=await r.json();if(d.ok)return d;if(r.status===429){await sleep(2000*i);continue}}catch{}return{ok:false}}
async function tgCall(e,method,body){for(let i=1;i<=4;i++)try{const r=await fetchTimeout(`https://api.telegram.org/bot${e.BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)},TG_TIMEOUT),d=await r.json();if(d.ok)return d;if(r.status===429){await sleep(2000*i);continue}return d}catch(x){if(i===4)throw x;await sleep(500*i)}}
async function sendMessage(e,chat,text,options={}){try{await tgCall(e,"sendMessage",{chat_id:chat,text,...options})}catch(x){console.error("TG SEND",x)}}
async function fetchTimeout(url,opt,ms){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}catch(x){if(x.name==="AbortError")throw Error(`Request timeout (${ms/1000}s)`);throw x}finally{clearTimeout(t)}}

// Cloudflare deployment
// Required: BOT_STATE = KV namespace, UPLOAD_QUEUE = Queue binding.
// Secrets/vars: BOT_TOKEN, GITHUB_TOKEN.
// Deploy this file as worker.js using your normal Cloudflare deploy command.
